[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
non_custodial_escrow = "F9cp6XU8hwEaM7hBgAXtURGkHTnGh6xWKKrQzLV4Prda"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=51e0da6e-3012-4def-8966-65a5397ff53d"
wallet = "~/.config/solana/id.json"
# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
